README.md, lib/lrama/output.rb, sample/parse.y, spec/lrama/output_spec.rb, template/bison/yacc.c
Add a sample parser file ("sample/parse.y") because ruby/ruby parse.y requires preprocess.
Supporting "sample/parse.y", need to extract some template code into "lib/lrama/output.rb".
=> Sample parser file

.github/workflows/test.yaml, lib/lrama/output.rb, lib/lrama/states.rb
* [Use Array#& instead of Array#intersection](https://github.com/yui-knk/lrama/commit/2c8fd5dfe949462987069359d0f929d6e2a940bb)
* [Extract Lrama::Output#eval_template](https://github.com/yui-knk/lrama/commit/c681ad45ece215aa861e2dcafc569a8758f3ad42)
* [Support older ERb](https://github.com/yui-knk/lrama/commit/530294052642d78cfd1012de3d4c6ba82b15d6c8)
* [Remove indent at preprocessor directive for tool/ytab.sed](https://github.com/yui-knk/lrama/commit/8a621c8673393b065e34b55f48c83b5bb140d11a)
=> Backward compatibility

.github/workflows/test.yaml
Template file on ruby/ruby was changed by https://github.com/ruby/ruby/pull/7807. Then copying template in CI breaks build.
=> Temporarily stop copying template to fix CI

lib/lrama/command.rb
When `-` is given as grammar file name, reads the grammar source from STDIN, and takes the next argument as the input file name.  This mode helps pre-process a grammar source.
=> Add stdin mode

lib/lrama/lexer.rb, spec/fixtures/common/basic.y, spec/lrama/lexer_spec.rb
I'm not familiar with YACC/Bison, so I'm not sure if this fix is the correct and expected one. I welcome any comments.
=> Support `//` style comment

.github/workflows/test.yaml
After https://github.com/ruby/ruby/pull/7798, ruby uses lrama as default then no need to pass YACC anymore.
=> Stop passing YACC arg for make

README.md, sample/calc.y
- Add calc.y to usage
- Add message to calc.y
=> Add calc.y to usage

lib/lrama/grammar.rb, lib/lrama/states.rb
Found by trial application of Steep
=> Prevent NoMethodError in generating an error message

.github/workflows/test.yaml, .gitignore, rbs_collection.lock.yaml, rbs_collection.yaml
Extracted changes related to rbs_collection from #19, following the comment below:
https://github.com/ruby/lrama/pull/19#issuecomment-1553870369
> - rbs_collection.yaml を入れるのは必要なので別のPRをつくっていただいてやるのがいいとおもいます
=> Add rbs_collection.yaml

Steepfile, sig/lrama/warning.rbs
Added warning.rbs ~~based on #19~~.
- The auto-generated type of `@out` was `IO`, but `@out` can be a String in [tests](https://github.com/ruby/lrama/blob/4b424415b49827758c99c8f4e74eb1dd71c80ef2/spec/lrama/context_spec.rb#L3).
- I could write the type of `message` to be `string & _ToS`, but I think it would be too complex.
=> Add warning.rbs

.github/workflows/test.yaml
lrama_0_4 is kept for Bison compatible branch. However lrama master branch is actively developed for ruby master branch. This commit changes test target to ruby_3_2.
=> Change integration test target from master to ruby_3_2

lib/lrama/grammar.rb, lib/lrama/lexer.rb, lib/lrama/parser.rb, lib/lrama/parser/token_scanner.rb, spec/lrama/lexer_spec.rb, spec/lrama/parser_spec.rb
In this pull request, I have implemented the [Named References](https://www.gnu.org/software/bison/manual/html_node/Named-References.html) concept from bison.
By merging this pull request, it will be possible to refer to the value by its symbol in the rule or its alias from within the action.
- Detect and tokenize the named references declaration
- Make references from named references in actions
- Change some grammar parameters
- Add alias to Token class
- Rename number in the Reference class to value because there is now a case where a string is assigned in addition to a number.
- Add a test case
=> Implement named references

spec/fixtures/command/basic.y, spec/lrama/command_spec.rb
- In todo list, https://docs.google.com/document/d/1EAZzYMXBOdzK-6mMIj2YNJxZZRVcpJxE7-4zXbHn8JA/edit#heading=h.ncudzyf4x3b
- This PR add tests corresponding to the following implementation https://github.com/ruby/lrama/pull/8
- Add tests in command_spec.rb
- normal mode case(`e.g., lrama -d parse.y -o parse.c`)
- stdin mode case(`e.g., ruby tool/id2token.rb parse.y | lrama -d - parse.y -o parse.c`)
- invalid cases
- I added spec/fixtures/command/basic.y to use normal input test.
- I copied a grammar file from sample/calc.y to spec/fixtures/command. The contents of the file do not have significant meaning.
- If the above approach is inappropriate, could you please give me some advice?
=> Add tests for stdin mode

lib/lrama/state.rb, lib/lrama/state/resolved_conflict.rb
- Separate  ResolvedConflict from lrama/state.rb
- Add lrama/state/resolved_conflict.rb
=> Refactor lrama/state.rb 

spec/lrama/integration_spec.rb
Some compilers warn `yynerrs` in the tests.
```
/tmp/test.c:1268:9: warning: variable 'yynerrs' set but not used
[-Wunused-but-set-variable]
int yynerrs = 0;
^
1 warning generated.
/tmp/test.c:1258:9: warning: variable 'yynerrs' set but not used
[-Wunused-but-set-variable]
int yynerrs = 0;
^
1 warning generated.
```
=> Suppress unused-but-set-variable warnings

.gitignore, Gemfile, spec/spec_helper.rb
Hello, 
I have added `simplecov` to help tracking the tests coverage.
(Please let me know if you would prefer me to follow any structure when opening a PR.)
=> Added gem to help tracking the code coverage of the tests

lib/lrama/states.rb
Replace each with transform_values in direct_read_sets, read_sets, follow_sets and la methods.
=> Prefer transform_values in Lrama::States

lib/lrama/grammar/symbol.rb
Simplify display_name and enum_name methods by removing if-else and using non-word character class.
=> Refactor Lrama::Grammar::Symbol

lib/lrama/digraph.rb
Skip ``@result`` reassignment to the same value.
=> Early break and safe navigation to Lrama::Digraph#traverse

lib/lrama/parser/token_scanner.rb
Avoid calling current_token twice with safe navigation and using the return value of next.
=> Minimize current_token calls in Lrama::Parser::TokenScanner

lib/lrama/grammar.rb, lib/lrama/grammar/aux.rb, lib/lrama/grammar/auxiliary.rb
Can not use "aux" for file name in Windows.
=> Rename Aux to Auxiliary

.github/workflows/test.yaml, Gemfile, lib/lrama/command.rb
Add Add Windows CI to detect errors only happen on Windows environment, like https://github.com/ruby/lrama/pull/82.
=> Add Windows CI

lib/lrama/output.rb
String#split without arg depends on "$;", however it's better to not depend on "$;" for supporting multiple ruby version.
This is based on suggestion by nobu
https://github.com/ruby/lrama/commit/518aefd11527514b42dbdb5402694e37a34b9d00#r124738493
=> Refactor #extract_param_name

lib/lrama/lexer.rb, spec/lrama/lexer_spec.rb
A regexp `/@(\d)+/` seems wrong because this only captures the last digit in `$1`. It may not be intended.
This fixes the regexp and also adds new test cases for some tokens in user codes.
=> Fix lexing `@10` in user codes correctly

exe/lrama, lib/lrama/context.rb, lib/lrama/counterexamples.rb, lib/lrama/grammar.rb, lib/lrama/grammar/code.rb, lib/lrama/lexer.rb, lib/lrama/state.rb, lib/lrama/states.rb, lib/lrama/states_reporter.rb, spec/lrama/command_spec.rb, spec/lrama/counterexamples_spec.rb, spec/lrama/lexer_spec.rb, spec/lrama/output_spec.rb, spec/lrama/parser_spec.rb
This PR fix trivial formatting
- Remove unnecessary empty lines
- Remove redundant Object#to_s
- Remove unreachable code
- Remove redundant assignment
- Use min_by instead of sort_by...first
- Remove redundant string escape
- Remove excessive whitespace
- Remove unnecessary spacing
- Remove empty comment
=> Fix trivial formatting

lib/lrama/grammar.rb, lib/lrama/lexer.rb, lib/lrama/lexer/token.rb, lib/lrama/parser.rb, lib/lrama/states.rb, spec/lrama/states_spec.rb
This only specifies precedence and not specify associativity then a conflict is unresolved if precedence is same.
=> Implement %precedence Operator Precedence

lib/lrama/lexer.rb, lib/lrama/lexer/token.rb, spec/lrama/integration_spec.rb
Identifier in `@left.first_line` in action should be parsed as `@left` not `@left.first_line`. If identifier includes '.' and '-', it should be wrapped with brackets.
=> Fix to not include '.' and '-' into identifier without brackets

lib/lrama/digraph.rb, rbs_collection.lock.yaml, sig/lrama/digraph.rbs
`Digraph#traverse` push argment first. This means while loop stops before stack to be empty because it will be break if argment is popped. Checking the result of `@stack.pop` in while condition expr, so that we can ensure `z` to be not nil on semantics level.
=> Make sure `z` to be not nil

spec/lrama/grammar/code_spec.rb
Before this commit, `rspec spec/lrama/grammar/code_spec.rb` failed with NameError.
```
NameError:
uninitialized constant T
```
=> Make "spec/lrama/grammar/code_spec.rb" runnable independently

Steepfile, sig/lrama/lexer/token/type.rbs
I was planning to type-check `symbol.rb`, but I realized that I need `grammar.rb`, `lexer/token.rb`, and `lexer/token/type.rb`.
I'm working on preparing them in order, and this is going to be the first step in that process.
=> add lexer/token/type.rbs

sig/lrama/lexer/token/type.rbs
I've made the requested revisions to the previously PR(#114).
Also, I received guidance on #types in ruby-jp and added type definitions for the initialize method.
=> fix lexer/token/type.rbs

.github/workflows/test.yaml
The job is failed if there is any diff between `lib/lrama/new_parser.rb` and one generated from `parser.y`.
For example, https://github.com/yui-knk/lrama/commit/12558a7df833b56e9ec18448143c0962bec5fcde
=> Check parser.rb is is up to date in check-misc job

.github/workflows/codespell.yaml, lib/lrama/context.rb
This PR adds spell checking GitHub Actions workflow and fixes typos.
How about the following spell check by CI?
- https://github.com/codespell-project/codespell
The run detected the following spelling errors:
https://github.com/ruby/lrama/actions/runs/6520864200/job/17708868735?pr=120
```
Error: ./lib/lrama/context.rb:173: lenght ==> length
Error: ./lib/lrama/context.rb:217: assinged ==> assigned
Error: ./lib/lrama/context.rb:262: replase ==> replace, relapse, rephase
Error: ./lib/lrama/context.rb:275: replase ==> replace, relapse, rephase
```
=> Add spell checking GitHub Actions workflow

lib/lrama/option_parser.rb, spec/lrama/option_parser_spec.rb
```diff
❯ exe/lrama --help                                     
Lrama is LALR (1) parser generator written by Ruby.
Usage: lrama [options] FILE
+STDIN mode:
+lrama [options] - FILE               read grammar from STDIN
Tuning the Parser:
-S, --skeleton=FILE              specify the skeleton to use
-t                               reserved, do nothing
Output:
-h, --header=[FILE]              also produce a header file named FILE
-d                               also produce a header file
-r, --report=THINGS              also produce details on the automaton
--report-file=FILE           also produce details on the automaton output to a file named FILE
-o, --output=FILE                leave output to FILE
--trace=THINGS               also output trace logs at runtime
-v …
```
=> Add description of STDIN mode to help command

spec/lrama/context_spec.rb, spec/lrama/states_spec.rb
We are migrating Lrama's parser from hand written parser to LR parser generated by Racc. Replacing Parser with NewParser to prevent regression.
=> Use NewParser in spec files if possible

lib/lrama/new_parser.rb, parser.y, spec/lrama/new_parser_spec.rb
- Raise error when a identifier or a character appears after %prec seen
- Raise error when multiple user codes appears after %prec seen
=> Replace NewParser with Parser #4

.github/workflows/test.yaml
=> Add 2.5 for test-ruby CI job target

template/bison/yacc.c
If `output.include_header` is not defined, all contents in yacc.h are expanded to C file. Therefore `end` should be just before `b4_declare_symbol_enum`.
=> Fix the location of `end`

lib/lrama/new_lexer.rb, spec/lrama/new_parser_spec.rb
- Parse some escape characters
=> Replace NewParser with Parser #6

lib/lrama/option_parser.rb, spec/lrama/option_parser_spec.rb
In bison it is `-H` but in lrama it is `-h`.
How about making it available in `-H` as well?
Also, how about indicating that `-h` is deprecated in the help command as a soft deprecation?
=> Allow `-H` option to also generate a header file with the specified name

template/bison/yacc.c
Resolve: https://github.com/yui-knk/ruby/actions/runs/6545361161/job/17773670072
=> Add a newline at the end of C_DECLARATION in epilogue

lib/lrama/grammar.rb
```
❯ find ./ -type f -print | xargs grep 'create_token'
.//lib/lrama/grammar.rb:    def create_token(type, s_value, line, column)
```
=> Remove unused method

lib/lrama/command.rb, lib/lrama/parser.rb, parser.y, spec/lrama/context_spec.rb, spec/lrama/counterexamples_spec.rb, spec/lrama/output_spec.rb, spec/lrama/parser_spec.rb, spec/lrama/states_spec.rb
This PR is improve an error message for ParseError.
The file name and the source of the error location are now displayed.
When you have a file named `parse.y` like this:
```
%{
// Prologue
%}
%expect invalid
%%
program: /* empty */
;
INPUT
```
When lrama is executed, it displays an error as follows:
```
❯ lrama parse.y 
parser.y:416:in `on_error': parse.y:5:14: parse error on value #<struct Lrama::Lexer::Token type=#<struct Lrama::Lexer::Token::Type id=19, name="Ident">, s_value="invalid", alias=nil> (IDENTIFIER) (Racc::ParseError)
%expect invalid
^
from racc/parser.rb:286:in `_racc_do_parse_c'
from racc/parser.rb:286:in `do_parse'
from parser.y:400:in `block in parse'
from /Users/yudai.takada/ydah/lrama/lib/lrama/report/duration.rb:14:in `report_duration'
from parser.y:396:in `parse' …
```
=> Improve an error message for ParseError

Rakefile
So that CI check-misc job fails when racc command fails because of "terminal XXX not declared as terminal" error for example.
=> Use `sh` method defined by Rake to execute racc commmand

Steepfile, sig/lrama/lexer/token.rbs
=> add lexer/token.rbs

template/bison/yacc.c
```
❯ exe/lrama -d sample/parse.y -o calc.c && gcc -Wall calc.c -o calc
sample/parse.y:8:31: error: unknown type name 'YYSTYPE'
static enum yytokentype yylex(YYSTYPE *lval, YYLTYPE *yylloc);
^
sample/parse.y:8:46: error: unknown type name 'YYLTYPE'
static enum yytokentype yylex(YYSTYPE *lval, YYLTYPE *yylloc);
^
sample/parse.y:9:21: error: unknown type name 'YYLTYPE'
static void yyerror(YYLTYPE *yylloc, const char *msg);
^
calc.c:1201:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
int yynerrs = 0;
^
1 warning and 3 errors generated.
```
=> Fix unknown type error when using YYSTYPE or YYLTYPE

lib/lrama/parser.rb, parser.y
Follow up: https://github.com/ruby/lrama/pull/168/commits/9eff5048c160dc5b339bdfbdbf6e98fe0aff421f
=> Extract C_DECLARATION end process to a private method

lib/lrama/grammar.rb
`#build_references` is called inside of `#extract_references`.
=> Do not need to call `#build_references` in `#build_code`

lib/lrama/command.rb, lib/lrama/grammar.rb, lib/lrama/lexer.rb, lib/lrama/lexer/token.rb, lib/lrama/option_parser.rb, lib/lrama/parser.rb, parser.y, spec/fixtures/parameterizing_rules/list.y, spec/fixtures/parameterizing_rules/nonempty_list.y, spec/fixtures/parameterizing_rules/option.y, spec/lrama/command_spec.rb, spec/lrama/parser_spec.rb
This PR is implement parameterizing rules.
=> Implement parameterizing rules

lib/lrama/parser.rb, parser.y, spec/lrama/parser_spec.rb
```
❯ exe/lrama -d test.y                         
parser.y:400:in `on_error': a.y:5:7: parse error on value #<struct Lrama::Lexer::Token::Ident s_value="invalid", alias_name=nil> (IDENTIFIER) (Racc::ParseError)
%expect invalid
^^^^^^^
from racc/parser.rb:276:in `_racc_do_parse_c'
from racc/parser.rb:276:in `do_parse'
from parser.y:386:in `block in parse'
from /ydah/lrama/lib/lrama/report/duration.rb:14:in `report_duration'
from parser.y:381:in `parse'
from /ydah/lrama/lib/lrama/command.rb:11:in `run'
from exe/lrama:6:in `<main>'
```
=> Add the starting position to the location information

lib/lrama/grammar/code/initial_action_code.rb, lib/lrama/grammar/code/printer_code.rb, lib/lrama/grammar/code/rule_action.rb, lib/lrama/grammar/reference.rb, lib/lrama/grammar/rule_builder.rb, lib/lrama/lexer/token/user_code.rb, sig/lrama/grammar/reference.rbs, spec/lrama/grammar/rule_builder_spec.rb
So that `Reference#name` (String) is not overwritten with index (Integer).
=> Separate Reference value into index and name

lib/lrama/context.rb
```
❯ ruby -w exe/lrama -d sample/parse.y
/ydah/lrama/lib/lrama/context.rb:370: warning: assigned but unused variable - state_id
/ydah/lrama/lib/lrama/context.rb:370: warning: assigned but unused variable - froms_and_tos
```
=> Fix warning for assigned but unused variable

lib/lrama/lexer/token.rb
Some tokens doesn't have `location`. `#to_s` raises NoMethodError for such cases if the method uses `line` and `column`.
=> Use location for `#to_s`

Rakefile
This PR is add `spec` and `steep check` to Rake's default tasks.
How about just running the following command to check them all together?
```sh
❯ bundle exec rake   
```
=> Add `spec` and `steep check` to Rake's default tasks

Steepfile, lib/lrama/grammar.rb, lib/lrama/grammar/code/rule_action.rb, lib/lrama/grammar/reference.rb, lib/lrama/grammar/rule.rb, lib/lrama/grammar/rule_builder.rb, sig/lrama/grammar/reference.rbs, sig/lrama/grammar/rule.rbs, sig/lrama/grammar/rule_builder.rbs, spec/lrama/grammar/code_spec.rb, spec/lrama/grammar/rule_builder_spec.rb, spec/lrama/parser_spec.rb
Rule build process is a bit complicated. `new_token` (`"@1"`) is created
when derived rule is created. Original rule requires `new_token`, but
derived rule needs to refer to original rule.
We can avoid such complex order of rule generation by lazy reference resolution.
This PR also fixes a bug of derived rule for mid rule action referring to wrong LHS, mentioned by https://github.com/ruby/lrama/pull/195#issuecomment-1806217091
=> Lazy reference resolution

lib/lrama/grammar.rb, lib/lrama/grammar/rule_builder.rb, lib/lrama/parser.rb, parser.y, spec/fixtures/parameterizing_rules/separated_list.y, spec/fixtures/parameterizing_rules/separated_nonempty_list.y
Char (`'c'`) is different from String (`"string"`).
Char is treated as terminal and String is an alias of a token
like `%token tEQEQ  "=="`.
These grammar files use String for separator but don't define
it as an alias of token.
Char is enough for these cases.
=> Remove separator

lib/lrama/grammar/rule_builder.rb
This instance variable will manage derived rules
other than midrule actions, for example parameterizing, parser state update syntax.
=> Rename instance variable

spec/lrama/integration_spec.rb, template/bison/yacc.c
Before
```
❯ bundle exec rspec                    
....................................................../var/folders/91/c1qqv7c94yz_cp1dz10bmwq00000gp/T/test.c:1179:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
int yynerrs = 0;
^
1 warning generated.
....../var/folders/91/c1qqv7c94yz_cp1dz10bmwq00000gp/T/test.c:1208:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
int yynerrs = 0;
^
1 warning generated.
./var/folders/91/c1qqv7c94yz_cp1dz10bmwq00000gp/T/test.c:1196:9: warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
int yynerrs = 0;
^
1 warning generated.
..........................................................................
Finished in 6.89 seconds (files took 0.51071 seconds to load)
135 examples, 0 …
```
=> Silence compiler warnings

lib/lrama/lexer.rb
```
❯ exe/lrama --trace=time -o parse.tmp.c --header=parse.tmp.h parse.tmp.y
parse    4.38929 s
compute_lr0_states    0.88006 s
compute_direct_read_sets    0.06813 s
compute_reads_relation    0.01174 s
compute_read_sets    0.04809 s
compute_includes_relation    0.72033 s
compute_lookback_relation    1.40715 s
compute_follow_sets    0.12471 s
compute_look_ahead_sets    1.00162 s
compute_conflicts    0.06503 s
compute_default_reduction    0.00617 s
compute_yydefact    0.08520 s
compute_yydefgoto    0.07973 s
sort_actions    0.00674 s
compute_packed_table    0.41180 s
render    0.09383 s
```
```
❯ exe/lrama --trace=time -o parse.tmp.c --header=parse.tmp.h parse.tmp.y
parse    0.93149 s
compute_lr0_states    0.90139 s
compute_direct_read_sets    0.07115 s
compute_reads_relation    0.01218 s …
```
=> Improved lexer speed

lib/lrama/lexer.rb, spec/lrama/lexer_spec.rb
Currently, the lexer produces an identifier token for `// foo <EOF>` because it only skips `//` when a line comment has no newline.
We can create such a funny example:
```
$ ruby -e 'print ?/*20_000' > p.y
$ exe/lrama p.y
parser.y:459:in `on_error': p.y:10001:-1: parse error on value "$" ($end) (Racc::ParseError)
...
```
Why the reported line number is `10001`??
=> Lex a line comment without newline correctly

lib/lrama/grammar/parameterizing_rules/builder/list.rb, lib/lrama/grammar/parameterizing_rules/builder/nonempty_list.rb, lib/lrama/grammar/parameterizing_rules/builder/separated_list.rb, lib/lrama/grammar/parameterizing_rules/builder/separated_nonempty_list.rb
Because these comma are not part of rule.
=> Remove comma from expanded rule examples

lib/lrama/grammar/parameterizing_rules/builder/separated_list.rb, spec/lrama/parser_spec.rb
Before
```
program: separated_list(',', number)
↓
program: separated_list_number
separated_list_number: ε
separated_list_number: number
separated_list_number: separated_list_number ',' number
```
After
```
program: separated_list(',', number)
↓
program: separated_list_number
separated_list_number: ε
separated_list_number: separated_nonempty_list_number
separated_nonempty_list_number: number
separated_nonempty_list_number: separated_nonempty_list_number ',' number
```
=> Fix separated_list expansion

lib/lrama/grammar/symbol.rb, spec/lrama/grammar/rule_builder_spec.rb, spec/lrama/grammar/symbol_spec.rb, spec/lrama/parser_spec.rb, spec/spec_helper.rb
This change improves performance about 30% by skipping object comparison of `Lrama::Lexer::Token`.
`Lrama::Grammar::Symbol` is an unique object
then it's ok to use comparison methods inherited from `Object`.
```
$ time bundle exec exe/lrama --trace=time -o parse.tmp.c --header=parse.tmp.h tmp/parse.tmp.y
parse    0.71535 s
compute_lr0_states    0.30997 s
compute_direct_read_sets    0.03551 s
compute_reads_relation    0.00628 s
compute_read_sets    0.01906 s
compute_includes_relation    0.38075 s
compute_lookback_relation    0.76338 s
compute_follow_sets    0.05411 s
compute_look_ahead_sets    0.55136 s
compute_conflicts    0.03092 s
compute_default_reduction    0.00360 s
compute_yydefact    0.04675 s
compute_yydefgoto    0.01515 s
sort_actions    0.00385 s
compute_packed_table    0.30613 …
```
=> Performance improvement

.github/workflows/test.yaml
Sometimes `choco install winflexbison` fails, so how about retrying?
- https://github.com/ruby/lrama/actions/runs/7019310484/job/19096471447
=> Retry if choco install winflexbison fails

lib/lrama/grammar.rb, lib/lrama/grammar/parameterizing_rules/builder.rb, lib/lrama/grammar/parameterizing_rules/builder/base.rb, lib/lrama/grammar/parameterizing_rules/builder/list.rb, lib/lrama/grammar/parameterizing_rules/builder/nonempty_list.rb, lib/lrama/grammar/parameterizing_rules/builder/option.rb, lib/lrama/grammar/parameterizing_rules/builder/separated_list.rb, lib/lrama/grammar/parameterizing_rules/builder/separated_nonempty_list.rb, lib/lrama/grammar/rule.rb, lib/lrama/grammar/rule_builder.rb, lib/lrama/parser.rb, parser.y, sig/lrama/grammar/parameterizing_rules/builder.rbs, sig/lrama/grammar/rule.rbs, sig/lrama/grammar/rule_builder.rbs, spec/fixtures/parameterizing_rules/option_with_tag.y, spec/lrama/parser_spec.rb
This PR add support for type specification in parameterizing rules.
=> Add support for type specification in parameterizing rules

spec/fixtures/integration/line_number.l, spec/fixtures/integration/line_number.y, spec/lrama/integration_spec.rb, template/bison/yacc.c
`C_DECLARATION` includes new line after `"%{"` (prologue) or `"%%"` (epilogue) then adjust `#line` directive and source codes in template.
=> Fix the codes line numbers in prologue and epilogue

lib/lrama/grammar/parameterizing_rule_builder.rb, sig/lrama/grammar/parameterizing_rule_builder.rbs
To avoid confusing `args` with `token.args`.
=> Rename `ParameterizingRuleBuilder#args` to `#parameters`

lib/lrama/grammar/rule_builder.rb, lib/lrama/lexer.rb, lib/lrama/lexer/location.rb, lib/lrama/parser.rb, parser.y, sig/lrama/lexer/location.rbs, spec/fixtures/lexer/location.y, spec/lrama/grammar/rule_builder_spec.rb, spec/lrama/lexer/location_spec.rb, spec/lrama/lexer/token/user_code_spec.rb, spec/lrama/lexer_spec.rb, spec/lrama/parser_spec.rb
Before
```
Referring symbol `bodystmts` is not found. #<Lrama::Lexer::Token::UserCode:0x000000011cf324c0> location: (2572,21)-(2583,20) (RuntimeError)
```
After
```
tmp/parse.tmp.y:2578:50: Referring symbol `bodystmts` is not found. (RuntimeError)
RNODE_DEFS($$)->nd_defn = $bodystmts;
^^^^^^^^^^
```
=> Better error message

lib/lrama/lexer.rb
```
❯ ruby -w exe/lrama -d sample/parse.y --trace=time
/ydah/lrama/lib/lrama/lexer.rb:148: warning: character class has duplicated range: /[^\"'\{\}\n%}]+/
/ydah/lrama/lib/lrama/lexer.rb:148: warning: character class has duplicated range: /[^\"'\{\}\n}]+/
/ydah/lrama/lib/lrama/lexer.rb:148: warning: character class has duplicated range: /[^\"'\{\}\n}]+/
/ydah/lrama/lib/lrama/lexer.rb:148: warning: character class has duplicated range: /[^\"'\{\}\n}]+/
/ydah/lrama/lib/lrama/lexer.rb:148: warning: Unknown escape \Z is ignored: /[^\"'\{\}\n\Z]+/
/ydah/lrama/lib/lrama/lexer.rb:148: warning: Unknown escape \Z is ignored: /[^\"'\{\}\n\Z]+/
/ydah/lrama/lib/lrama/lexer.rb:148: warning: Unknown escape \Z is ignored: /[^\"'\{\}\n\Z]+/
/ydah/lrama/lib/lrama/lexer.rb:148: warning: Unknown escape \Z …
```
=> Fix warnings

.github/workflows/test.yaml
Lrama 0.5 targets ruby 3.3 then change the target of CI.
I will merge this PR once ruby_3_3 branch is created.
=> Change test-ruby target to ruby_3_3 branch

lib/lrama/grammar/type.rb
So that we can change id and tag to be a mandatory argument.
=> Make Type to be plain object

lib/lrama/grammar/rule_builder.rb, lib/lrama/lexer/token/instantiate_rule.rb, lib/lrama/parser.rb, parser.y, sig/lrama/grammar/rule_builder.rbs, sig/lrama/lexer/token/instantiate_rule.rbs
This tag specifies not type of lhs of the rule
but type of generated rule lhs. Therefore change it to be managed by InstantiateRule.
=> Move lhs_tag from RuleBuilder to InstantiateRule

lib/lrama/grammar/rule_builder.rb, lib/lrama/lexer/token.rb, sig/lrama/lexer/token.rbs, spec/lrama/grammar/rule_builder_spec.rb
When an out-of-range index:
```
| '!' command_call
{
$$ = call_uni_op(p, method_cond(p, $3, &@2), '!', &@1, &@$);
}
```
The error message isn't useful. 
```
/Users/nobu/src/ruby/master/src/tool/lrama/lib/lrama/grammar/rule_builder.rb:166:in `block (2 levels) in numberize_references': Can not refer following component. 3 >= 3. #<Lrama::Lexer::Token::UserCode:0x000000013307ada8> location: parse.y (2652,21)-(2654,20) (RuntimeError)
```
=> Print a part of grammar file when invalid referring number happens

.github/workflows/test.yaml, spec/lrama/integration_spec.rb
CI fails to install winflexbison because of checksum mismatch. Change to use msys2 to fix the issue.
See: https://github.com/ruby/lrama/actions/runs/7429169162/job/20217621117
=> Use msys2 instead of chocolatey to install flex

.github/workflows/test.yaml
Previously, Ruby versions in `test.yaml` were specified using an array. However, this PR has been changed to use the [ruby/actions](https://github.com/ruby/actions/blob/master/.github/workflows/ruby_versions.yml) workflow for version.
=> Use ruby/actions workflow for ruby versions

.github/workflows/test.yaml
```
❯ actionlint
.github/workflows/test.yaml:129:27: string should not be empty [syntax-check]
|
129 |         working-directory:
|                           ^
.github/workflows/test.yaml:134:27: string should not be empty [syntax-check]
|
134 |         working-directory:
|                           ^
```
refs: https://github.com/rhysd/actionlint
=> Use `working-directory: .` instead of `working-directory: `

lib/lrama/grammar/binding.rb, lib/lrama/grammar/parameterizing_rule/resolver.rb, lib/lrama/grammar/rule_builder.rb, sig/lrama/grammar/binding.rbs, sig/lrama/grammar/parameterizing_rule/resolver.rbs, sig/lrama/grammar/rule_builder.rbs, spec/fixtures/parameterizing_rules/user_defined_with_recursive.y, spec/lrama/parser_spec.rb
This PR fixes the issue of an infinite loop when there is a recurrent parameterizing rule call.
For example, the following rule would have resulted in an infinite loop.
```ruby
%rule list(X): /* empty */
| X
| list(X)
;
```
=> Fix an infinite loop issue with recurrent calls to parameterizing rule

lib/lrama/grammar/code/rule_action.rb
Rule action can not be referred.
=> Fix comments

lib/lrama/grammar/rule_builder.rb, spec/lrama/grammar/rule_builder_spec.rb
Before this commit, LHS is not included into check list of `candidates`. Therefore `$args` in the code below is valid reference and converted to the reference to LHS (`args`).
This commit change it to check both of LHS and RHS when resolve the named reference, so that the code is reported as duplicated reference.
```
args : ...
| args ',' arg_splat
{
$$ = rest_arg_append(p, $args, $arg_splat, &@$);
}
;
```
=> `RuleBuilder#numberize_references` should check LHS and RHS for duplication

.github/workflows/test.yaml, lib/lrama/grammar/stdlib.y, spec/fixtures/command/basic.y, spec/fixtures/lexer/location.y
ruby/ruby checks if C-sources are US-ASCII.
And Compilations failed with "invalid byte sequence in US-ASCII"
if Lrama codes include Non US-ASCII.
See:
* https://github.com/yui-knk/ruby/actions/runs/7675060037/job/20920736805
* https://github.com/yui-knk/ruby/actions/runs/7675060017/job/20920738516
=> Use only US-ASCII

lrama.gemspec
This PR added [metadata](https://guides.rubygems.org/specification-reference/#metadata) for [rubygems.org](https://rubygems.org/gems/lrama)
=> Add metadata for rubygems.org

lib/lrama/grammar/reference.rb, lib/lrama/grammar/rule_builder.rb, lib/lrama/lexer/token/user_code.rb, sig/lrama/grammar/reference.rbs, spec/lrama/lexer/token/user_code_spec.rb
This PR is separate number and index.
When Inlining is implemented, for example, if `$1` is expanded to multiple RHS tokens, `$2` needs to access `$2 + n` to actually access it. So, after the Inlining implementation, it needs resolves from number to index.
=> Separate number and index in `Grammar::Reference`

lib/lrama/lexer/token/user_code.rb
=> `#scan_reference` should fill `Reference#number` for `$:n`.

lib/lrama/grammar/symbols/resolver.rb, lib/lrama/lexer/token.rb, spec/lrama/grammar/symbols/resolver_spec.rb
Before
```
Symbol not found: #<Lrama::Lexer::Token::Ident:0x00000001027befa0> location: spec/fixtures/inlining/basic.y (26,29)-(26,31)
```
After
```
Symbol not found. value: `alias`, location: spec/fixtures/inlining/basic.y (26,29)-(26,31)
```
=> Improve error message for symbols

lib/lrama/option_parser.rb, spec/lrama/option_parser_spec.rb
Add "Valid Reports" and "Valid Traces" to the help message.
=> Show valid arguments for command line options

lib/lrama/grammar/rule_builder.rb, spec/lrama/integration_spec.rb, spec/lrama/parser_spec.rb
For example, if `printf("pair odd even:% d\n," $1); `was unable to access the pair side of` $$`with` $1`, fix this:
```
%rule pair(X, Y): X Y
{
$$ = $1 + $2;
printf("(%d, %d)\n", $1, $2);
}
;
stmt: pair(ODD, EVEN) <num> { printf("pair odd even: %d\n", $1); }
```
=> Fix an issue in a user-defined parameterizing rule where the caller cannot access `$$` in the rule

lib/lrama/lexer/grammar_file.rb, sig/lrama/lexer/grammar_file.rbs
In my environment, inspection of Lrama::State is too slowly.
After a little research, there are many inspections of Lrama::GrammarFile instances in Lrama::Token and I found printing the whole text of grammar file many times.
=> Truncate GrammarFile's @text when inspecting

lib/lrama/lexer/grammar_file.rb
It would be great if it could be shortened because it would be very difficult to see when debugging.
before:
```
#<Lrama::Lexer::Token::Ident:0x0000000104fd0fc0
@alias_name=nil,
@location=
#<Lrama::Lexer::Location:0x000000010516e5d0
@first_column=0,
@first_line=27,
@grammar_file=
#<Lrama::Lexer::GrammarFile:0x0000000104e975a0
@path="spec/fixtures/inlining/resolve_index.y",
@text=
"/*\n" +
" * This is comment for this file.\n" +
" */\n" +
"\n" +
"%{\n" +
"// Prologue\n" +
"static int yylex(YYSTYPE *val, YYLTYPE *loc);\n" +
"static int yyerror(YYLTYPE *loc, const char *str);\n" +
"%}\n" +
"\n" +
"%union {\n" +
"    int i;\n" +
"}\n" +
"\n" +
"%token <i> NUM\n" +
"%type <i> expression\n" +
"\n" +
"%rule %inline op  : '+' '=' { += }\n" +
"                  | '-' '-' '=' { -= }\n" +
" …
```
=> Omit too long text when printing module `Lrama::Lexer::GrammarFile` class

lib/lrama/command.rb, lib/lrama/grammar/rule.rb, lib/lrama/option_parser.rb, spec/lrama/command_spec.rb, spec/lrama/option_parser_spec.rb
The concept of merging actions was born in Inline. I think it would be useful to have an option to print the resolved action. However, we don't know what it is when I just display the action, so I've decided to print the rule and its corresponding action like this:. What do you think?
```
❯ exe/lrama --trace=actions sample/calc.y
Grammar rules with actions:
$accept -> list, YYEOF {}
list -> ε {}
list -> list, LF {}
list -> list, expr, LF { printf("=> %d\n", $2); }
expr -> NUM {}
expr -> expr, '+', expr { $$ = $1  +  $3; }
expr -> expr, '-', expr { $$ = $1  -  $3; }
expr -> expr, '*', expr { $$ = $1  *  $3; }
expr -> expr, '/', expr { $$ = $1  /  $3; }
expr -> '(', expr, ')' { $$ = $2; }
```
=> Introduce the `--trace=actions` option

lib/lrama/grammar/rule.rb, spec/lrama/command_spec.rb, spec/lrama/grammar/code_spec.rb, spec/lrama/states_spec.rb
It's confusing with `','` terminal symbol.
=> Remove `,` from Rule print format

lib/lrama/grammar/parameterizing_rule/rhs.rb, spec/fixtures/integration/user_defined_parameterizing_rules.y, spec/lrama/integration_spec.rb
```
1) integration user defined parameterizing rules prints messages corresponding to rules
Failure/Error: expect(out).to eq(expected)
expected: "(2, 3)\n(2, 3)\n(-2, -1)\npair even odd: 5\n(1, 0)\n(1, 0)\n(-2, -1)\npair odd even: 1\n"
got: "(2, 3)\n(3, 3)\n(-2, -1)\npair even odd: 5\n(1, 0)\n(0, 0)\n(-2, -1)\npair odd even: 1\n"
(compared using ==)
Diff:
@@ -1,9 +1,9 @@
(2, 3)
-(2, 3)
+(3, 3)
(-2, -1)
pair even odd: 5
(1, 0)
-(1, 0)
+(0, 0)
(-2, -1)
pair odd even: 1
```
=> Fix an error for `Lrama::Grammar::ParameterizingRule::Rhs#resolve_user_code` when multiple execute method

lib/lrama/grammar.rb, lib/lrama/grammar/rule_builder.rb
- Remove unnecessary empty line
- Enclose in parentheses where you assign in the if condition
=> Trivial fixes

lib/lrama/parser.rb, parser.y
racc's v1.8.0 has been released:
https://github.com/ruby/racc/releases/tag/v1.8.0
So we got a new grammar.
- https://github.com/ruby/racc/pull/222
This pull request uses `Option:? `. WDYT?
see: https://www.antlr.org/
=> Use `foo?` instead of `foo_opt`

lib/lrama/parser.rb, parser.y
The TODO added in the following PR will be eliminated: 
- https://github.com/ruby/lrama/pull/143
=> Use `string_as_id` instead of `STRING`

lib/lrama/grammar/binding.rb, sig/lrama/grammar/binding.rbs, spec/fixtures/parameterizing_rules/user_defined/with_action_and_named_references.y, spec/lrama/parser_spec.rb
This PR support for aliased Named References for actions of rhs in Parameterizing rules.
If there is a non-terminal symbol in the RHS of parameterizing rules as shown below, I want to access it in the Named Reference.
```
%rule sum(X, Y): X[summand] '+' Y[addend] { $$ = $summand + $addend }
;
```
=> Add support for aliased Named References for actions of rhs in Parameterizing rules

lib/lrama/command.rb, lib/lrama/grammar.rb, lib/lrama/grammar/code/rule_action.rb, lib/lrama/grammar/rule.rb, lib/lrama/states_reporter.rb, sig/lrama/grammar/rule.rbs
I saw a TODO in `lib/lrama/grammar/rule.rb` to rename the `to_s` method to the `display_name` method, so I renamed it.
=> Rename Lrama::Grammar::Rule#to_s to Lrama::Grammar:Rule::display_name

spec/lrama/grammar/symbols/resolver_spec.rb
```
❯ bundle exec rspec --warning
/ydah/lrama/spec/lrama/grammar/symbols/resolver_spec.rb:83: warning: assigned but unused variable - nterm1
................................................................................................................................................................................................................................
Finished in 8.23 seconds (files took 0.18522 seconds to load)
224 examples, 0 failures
```
=> Fix warning when execute rspec

lib/lrama/output.rb
=> Change String not to be reassigned

Gemfile, README.md
Occasionally, some changes require a verify in memory usage. We have actually verified this in the following.
- https://github.com/ruby/lrama/pull/428#issuecomment-2150177656
So, this PR describe Lrama's memory profiling method and add the necessary memory_profiler gem.
=> Change to allow verification of memory usage

lib/lrama/grammar/code/rule_action.rb
"rhs" is pronounced "ar-aitch-es." The initial sound is a vowel sound ("ar"), so "an rhs" is correct. 
"lhs" is pronounced "el-aitch-es." The initial sound is a vowel sound ("el"), so "an lhs" is correct.
Therefore, we should write:
- an RHS
- an LHS
=> Fix trivial typo in comment

sig/lrama/grammar.rbs, sig/lrama/options.rbs
- Fix an indentation in sig/lrama/options.rbs
- Fix rbs validate warning
```
❯ bundle exec rbs -I sig validate
W, [2024-06-07T16:09:23.137310 #4825]  WARN -- rbs: sig/lrama/grammar.rbs:74:19...74:37: `void` type is only allowed in return type or generics parameter (RBS::WillSyntaxError)
def validate!: () -> (void | bot)
^^^^^^^^^^^^^^^^^^
```
- Use void instead of bot?
=> Fix some rbs

lib/lrama/option_parser.rb, lib/lrama/states_reporter.rb, spec/lrama/option_parser_spec.rb, spec/lrama/states_spec.rb
Add report_unused_terms private method to Lrama::StatesReporter for `TODO Unused terms` in `lib/lrama/states_report.rb`
However, I am not sure if the output format is what it is supposed to be, so I would appreciate your comments if it is different.
=> Add support `--report=terms` option

lib/lrama/states_reporter.rb, spec/lrama/states_spec.rb
This PR improve `--report=terms` command.
Output `Unused Terms` only when there are unused terms.
Also, output the number of terms as follows:
Before:
```
Unused Terms
0 YYerror
2 YYUNDEF
3 '\\\\'
3 '\\13'
4 keyword_class2
5 tNUMBER
6 tPLUS
7 tMINUS
8 tEQ
9 tEQEQ
10 '>'
```
After:
```
11 Unused Terms
0 YYerror
1 YYUNDEF
2 '\\\\'
3 '\\13'
4 keyword_class2
5 tNUMBER
6 tPLUS
7 tMINUS
8 tEQ
9 tEQEQ
10 '>'
```
=> Improve `--report=terms` command

lib/lrama/option_parser.rb, lib/lrama/states_reporter.rb, spec/fixtures/common/basic.y, spec/lrama/lexer_spec.rb, spec/lrama/option_parser_spec.rb, spec/lrama/parser_spec.rb, spec/lrama/states_spec.rb
This PR, add an option to output the following report when there are unused rules.
```
1 Unused Rules
0 unused
State 1 conflicts: 2 shift/reduce, 1 reduce/reduce
: (snip)
```
=> Add support `--report=rules` option

template/bison/yacc.c
Fix: https://github.com/ruby/lrama/issues/442
Before:
```
❯ exe/lrama -d sample/calc.y -o calc.c && cc -Wall calc.c -o calc
❯ exe/lrama -d sample/calc.y -o calc.c && gcc -Wall calc.c -o calc
❯ exe/lrama -d sample/calc.y -o calc.c && c++ -Wall calc.c -o calc
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
calc.c:1199:40: error: default initialization of an object of const type 'const YYSTYPE' without a user-provided default constructor
YY_INITIAL_VALUE (static const YYSTYPE yyval_default;)
```
After:
```
❯ exe/lrama -d sample/calc.y -o calc.c && cc -Wall calc.c -o calc
❯ exe/lrama -d sample/calc.y -o calc.c && gcc -Wall calc.c -o calc
❯ exe/lrama -d sample/calc.y -o calc.c && c++ -Wall calc.c -o calc
clang: warning: treating 'c' …
```
=> Fix an error for initialization within YY_INITIAL_VALUE() with C++

lib/lrama/option_parser.rb, spec/lrama/option_parser_spec.rb
This PR will improve the `--report` option as follows:
- Add support `cex` and `none` option in report
- Improve help text for report
Before:
```
Output:
-H, --header=[FILE]              also produce a header file named FILE
-d                               also produce a header file
-r, --report=THINGS              also produce details on the automaton
--report-file=FILE           also produce details on the automaton output to a file named FILE
: (snip)
Valid Reports:
states itemsets lookaheads solved counterexamples all rules terms verbose
```
After:
```
Output:
-H, --header=[FILE]              also produce a header file named FILE
-d                               also produce a header file
-r, --report=REPO_THINGS         also produce details on the automaton
--report-file=FILE …
```
=> Improve `--report` option

README.md
This PR add RubyDoc documentation badge to README.md
=> chore: Add RubyDoc documentation badge to README.md

README.md
Adding a relative link pointing to [LEGAL.md](./LEGAL.md) file in the README.md to fix broken link and ensure easy access to Legal instructions.
=> Update link to LEGAL.md file in README.md

README.md
The rake command for building the parser was updated to use `bundle exec` to ensure it runs in the correct gem environment.
=> chore: Change rake command to use bundle exec in README

Steepfile, sig/lrama/grammar/parameterizing_rule/rhs.rbs, sig/lrama/grammar/rule.rbs, sig/lrama/grammar/rule_builder.rbs
Type-checked all Ruby files contained in the `grammar` directory. Fixed to pass inspection.
=> Check `grammar` directory and fix some types

lrama.gemspec
The gemspec files were updated to exclude the `sample` directory from the list of files included in the gem. This ensures that the `sample` directory is not included when building the gem.
=> chore: Exclude sample directory from gemspec files

lib/lrama/option_parser.rb, spec/lrama/option_parser_spec.rb
This PR adjusts the output of the trace help command.
Before
```
❯ exe/lrama -h
Lrama is LALR (1) parser generator written by Ruby.
Usage: lrama [options] FILE
STDIN mode:
lrama [options] - FILE               read grammar from STDIN
Tuning the Parser:
-S, --skeleton=FILE              specify the skeleton to use
-t                               reserved, do nothing
--debug                      display debugging outputs of internal parser
Output:
-H, --header=[FILE]              also produce a header file named FILE
-d                               also produce a header file
-r, --report=REPORTS             also produce details on the automaton
--report-file=FILE           also produce details on the automaton output to a file named FILE
-o, --output=FILE                leave output to FILE …
```
=> Adjust the output of the trace help command

lib/lrama/option_parser.rb, spec/lrama/option_parser_spec.rb
Add support for `-v` and `--vervose` options. These options align with Bison behavior.
```
❯ bison --help      
Usage: bison [OPTION]... FILE
Generate a deterministic LR or generalized LR (GLR) parser employing
LALR(1), IELR(1), or canonical LR(1) parser tables.
: (snip)
Output Files:
-H, --header=[FILE]           also produce a header file
-d                            likewise but cannot specify FILE (for POSIX Yacc)
-r, --report=THINGS           also produce details on the automaton
--report-file=FILE        write report to FILE
-v, --verbose                 same as '--report=state'
```
=> Add support `-v`, `--verbose` option

Steepfile, lib/lrama/states/item.rb, sig/lrama/grammar/rule.rbs, sig/lrama/states/item.rbs
This is the type definition of Item.rb added in [this PR](https://github.com/ruby/lrama/pull/458#discussion_r1682331387).
=> Add types to states

lib/lrama/parser.rb, parser.y
- Use new racc grammar `+`, `*`, `? `?
- Remove unnecessary line breaks
- Add `midrule_action` and `empty` and `empty` non-terminal symbols to organize
- Remove redundant non-terminal symbols.
=> Organize parser.y

.github/workflows/test.yaml, sample/parse.y, spec/fixtures/integration/named_references.y, spec/fixtures/integration/typed_midrule_actions.y, spec/lrama/integration_spec.rb, template/bison/yacc.c
follow up: https://github.com/ruby/lrama/pull/447
fix: https://github.com/ruby/lrama/issues/442
=> Add CI env for C++ and fix errors and warnings when compiling as C++

NEWS.md
Split off from https://github.com/ruby/ruby/pull/12322
=> [DOC] Add syntax highlighting to MarkDown code blocks

Gemfile, lib/lrama/bitmap.rb, lib/lrama/grammar.rb, lib/lrama/grammar/parameterizing_rule/rhs.rb, lib/lrama/grammar/rule_builder.rb, lib/lrama/lexer/token/user_code.rb, lib/lrama/state/reduce.rb, rbs_collection.lock.yaml
The following warnings and errors have been fixed as a result of the version update:
```
bundle exec steep check
............F.........................F..................................F...FF.......F......
lib/lrama/grammar/parameterizing_rule/rhs.rb:19:23: [warning] Empty hash doesn't have type annotation
│ Diagnostic ID: Ruby::UnannotatedEmptyCollection
│
└           var_to_arg = {}
~~
lib/lrama/bitmap.rb:16:10: [warning] Empty array doesn't have type annotation
│ Diagnostic ID: Ruby::UnannotatedEmptyCollection
│
└       a = []
~~
lib/lrama/grammar/rule_builder.rb:70:28: [warning] Empty array doesn't have type annotation
│ Diagnostic ID: Ruby::UnannotatedEmptyCollection
│
└         resolved_builders = []
~~
lib/lrama/lexer/token/user_code.rb:19:23: [warning] Empty array doesn't have …
```
=> Bump rbs from v3.6.0 to v3.7.0 and steep from v1.8.0 to v1.8.1

lib/lrama/counterexamples/derivation.rb, spec/lrama/counterexamples_spec.rb
This PR fix an error when `str.length` is greater than `length`. 
Reproduced by parse.y below:
https://gist.github.com/ydah/70186de8a1ff14fa2cd16b338b9fc0e0
=> Fix an error when `str.length` is greater than `length`

lib/lrama/grammar.rb, lib/lrama/grammar/symbols/resolver.rb, lib/lrama/lexer.rb, lib/lrama/parser.rb, parser.y, spec/lrama/diagnostics_spec.rb, spec/lrama/grammar/code_spec.rb, spec/lrama/parser_spec.rb
This PR add support for %type declarations using `%nterm` in Nonterminal Symbols. https://www.gnu.org/software/bison/manual/html_node/Type-Decl.html
=> Add support for %type declarations using `%nterm` in Nonterminal Symbols

.github/workflows/test.yaml
Ref: https://github.com/ruby/ruby/blob/354e790794d9fd4996172da9235e3b09fcb3e4ca/.github/workflows/parsey.yml#L76-L83
=> Specify `--parser` for RUN_OPTS and SPECOPTS when run test-all

README.md
Ruby 3.4 has been released. Therefore, a[ lrama_0_6 branch will be create](https://github.com/ruby/lrama/tree/lrama_0_6), and the README will be update. 
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
---
(just a question)
Do we need to create and release v7.0 from the following tags?
https://github.com/ruby/lrama/tree/v0.6.11
=> Update README.md in versions and branches

Gemfile, lib/lrama/bitmap.rb, sig/generated/lrama/bitmap.rbs, sig/lrama/bitmap.rbs
I'll be installing rbs-inline, which we discussed previously.
rbs-inline requires writing the type information to `.rb` files and generating `.rbs` files with `rbs-inline --output`.
ref: https://github.com/soutaro/rbs-inline?tab=readme-ov-file#usage
I were also considering installing rubocop-on-rbs, but decided to pass on it because rubocop has not use yet.
=> Use rbs-inline and rewrite bitmap.rb

lib/lrama/lexer.rb
This pull request changes the `StringScanner#getch` to read one character at a time and optimizes Lexer's comment reading.
The effect is seen when there are many comments.
```yacc
/*
* Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis hendrerit, mi non eleifend aliquet, arcu lectus vulputate est, in suscipit lacus nibh a ligula. Nulla non mi sit amet lectus malesuada elementum et sed ex. Nam porttitor ut urna id consequat. Sed neque ex, feugiat ut convallis sit amet, laoreet vitae sapien. Aliquam vestibulum elit mauris, eu ornare leo consectetur nec. Suspendisse bibendum blandit pretium. Suspendisse eget tortor non libero sodales aliquam id vel risus.
*
* Maecenas ac cursus velit. Sed vehicula nisl mattis eros malesuada, eu volutpat lorem volutpat. Mauris et metus venenatis, …
```
=> Optimize Lexer comment reading

Steepfile, lib/lrama/trace_reporter.rb, sig/generated/lrama/trace_reporter.rbs
This PR add RBS type signatures for TraceReporter and generate RBS file.
=> Add RBS type signatures for TraceReporter and generate RBS file

Steepfile, lib/lrama/logger.rb, sig/generated/lrama/logger.rbs
This PR add RBS type signatures for Logger and generate RBS file.
=> Add RBS type signatures for Logger and generate RBS file

lib/lrama/grammar.rb
Just change use `@rule_builders.any?(&:has_inline_rules?)`
=> Simplify inline rule resolution using shorthand syntax for block arguments

.github/workflows/test.yaml, spec/lrama/integration_spec.rb
This PR adds GitHub Actions jobs for multiple C language compilers. Specifically, it introduces tests for both cc and clang.
=> Add test job for multiple compilers for C

lib/lrama/grammar/binding.rb, lib/lrama/grammar/rule_builder.rb, sig/lrama/grammar/binding.rbs, sig/lrama/grammar/rule_builder.rbs
This PR move processing of lhs_s_value method to Binding class.
=> Move processing of lhs_s_value method to Binding class

lib/lrama/option_parser.rb, spec/lrama/option_parser_spec.rb
This PR change the `-t` option, which was reserved, to match bison, so that it works the same as `--debug`.
```
❯ bison -h
Usage: bison [OPTION]... FILE
: (snip)
Tuning the Parser:
-L, --language=LANGUAGE          specify the output programming language
-S, --skeleton=FILE              specify the skeleton to use
-t, --debug                      instrument the parser for tracing
^^
```
=> Change the `-t` option, which was reserved, to match bison and behave the same as `--debug`

lib/lrama/grammar/rule.rb, lib/lrama/option_parser.rb, lib/lrama/trace_reporter.rb, sig/generated/lrama/trace_reporter.rbs, spec/lrama/option_parser_spec.rb, spec/lrama/trace_reporter_spec.rb
This PR, add 'only-explicit-rules' option to display explicit grammar rules.
--trace=rules:
```
❯ exe/lrama --trace=rules ./spec/fixtures/common/basic.y
Grammar rules:
$accept -> program EOI
program -> class
program -> '+' strings_1
program -> '-' strings_2
class -> keyword_class tSTRING keyword_end
$@1 -> ε
$@2 -> ε
class -> keyword_class $@1 tSTRING '!' keyword_end $@2
$@3 -> ε
$@4 -> ε
class -> keyword_class $@3 tSTRING '?' keyword_end $@4
strings_1 -> string_1
strings_2 -> string_1
strings_2 -> string_2
string_1 -> string
string_2 -> string '+'
string -> tSTRING
unused -> tNUMBER
```
--trace=only-explicit-rules:
```
❯ exe/lrama --trace=only-explicit-rules ./spec/fixtures/common/basic.y
Grammar rules:
$accept -> program EOI
program -> class
program -> '+' strings_1
program -> '-' …
```
=> Add 'only-explicit-rules' option to display explicit grammar rules

NEWS.md
=> Update NEWS.md for Lrama 0.7.0 release notes, adding support for `-t` option and tracing only explicit rules

.github/workflows/test.yaml
follow up:
- https://github.com/ruby/ruby/pull/12589
=> Retire ubuntu-20.04

lib/lrama/command.rb, lib/lrama/grammar.rb, lib/lrama/option_parser.rb, lib/lrama/options.rb, lib/lrama/parser.rb, lib/lrama/state.rb, lib/lrama/states.rb, lib/lrama/states/item.rb, parser.y, sig/lrama/options.rbs, spec/fixtures/integration/ielr.l, spec/fixtures/integration/ielr.y, spec/lrama/option_parser_spec.rb, spec/lrama/parser_spec.rb, spec/lrama/states_spec.rb
Support the generation of the IELR(1) parser described in this paper.
https://www.sciencedirect.com/science/article/pii/S0167642309001191
This PR will be ready for merging when the following is done.
- Currently, I have only created a grammar file and verified its operation in my local environment.
- The data structure is awful and needs to be improved because the priority was to achieve the expected results.
=> Support IELR(1) Parser Generation

.github/workflows/gh-pages.yml, .gitignore, .rdoc_options, Gemfile, Rakefile, doc/Index.md
This PR will allow you to review Lrama's documentation in the following GH pages: 
https://ruby.github.io/lrama/
Currently, Lrama documentation is not provided. Therefore, we would like to establish a system to provide documentation on the web.
I would like to add documents under the doc directory in markdown format.
=> Add GitHub Actions workflow for deploying Lrama documentation to GitHub Pages

lib/lrama/grammar.rb, lib/lrama/option_parser.rb, lib/lrama/options.rb, sig/generated/lrama/options.rbs, spec/lrama/option_parser_spec.rb
```
❯ exe/lrama --define=foo sample/calc.y
wrong array length at 0 (expected 2, was 1)
```
This is occurring and has been addressed below:
https://github.com/ruby/lrama/blob/7fa74d84a68b3632950b969d29ccf012a0ea4a42/lib/lrama/grammar.rb#L60
=> Fix an error when specify `--define=foo`

lib/lrama/option_parser.rb, lib/lrama/parser.rb, parser.y, spec/lrama/option_parser_spec.rb, spec/lrama/parser_spec.rb
Following bison's behavior:
```command
$ bison -h
Usage: bison [OPTION]... FILE
Generate a deterministic LR or generalized LR (GLR) parser employing
LALR(1), IELR(1), or canonical LR(1) parser tables.
: (snip)
Tuning the Parser:
-L, --language=LANGUAGE          specify the output programming language
-S, --skeleton=FILE              specify the skeleton to use
-t, --debug                      instrument the parser for tracing
same as '-Dparse.trace'
^^^^^^^^^^^^^^^^^^^^^^^
```
=> Enhance debug option handling to include 'parse.trace' definition

Rakefile
This allows us to merge the two commands that used to be executed when performing a steep check into a single command.
```
$ bundle exec rake rbs_inline
$ bundle exec rake steep
```
```
$ bundle exec rake steep
```
=> Make the rbs_inline task run when the steep task is run

lib/lrama/grammar.rb, lib/lrama/parser.rb, lib/lrama/warnings.rb, lib/lrama/warnings/required.rb, parser.y, sig/generated/lrama/warnings/required.rbs, spec/lrama/warnings/required_spec.rb
This PR adds a warning output when using %require, which exists only for compatibility with Bison. 
see: https://www.gnu.org/software/bison/manual/html_node/Require-Decl.html
=> Add warning output when using %require, which exists only for compatibility with Bison

spec/lrama/states_spec.rb
`expect` is bit confusing with `#expect` method in spec file.
=> Clarify `expect` to be `%expect`

lib/lrama/state.rb, spec/lrama/states_spec.rb
`#<ArgumentError: wrong number of arguments (given 2, expected 0)>` is raised from `#goto_follows` when `#item_lookahead_set` is called for a state
* whose `kernel.position` is 1
* previous state has internal dependencies or predecessor dependencies
In an added test case, state 0 is a previous state of state 2 and state 0 has an internal dependency on state 4.
Backtraces of failed test case is
```
1) Lrama::States#compute_ielr recompute states
Failure/Error: expect { states.compute_ielr }.not_to raise_error
expected no Exception, got #<ArgumentError: wrong number of arguments (given 2, expected 0)> with backtrace:
```
=> Fix ArgumentError

lib/lrama/states.rb
Fix following warnings:
```
❯ RUBYOPT=-w bundle exec rake
bundle exec racc parser.y --embedded -o lib/lrama/parser.rb -t --log-file=parser.output
/ydah/.rbenv/versions/3.5-dev/bin/ruby -I/ydah/.rbenv/versions/3.5-dev/lib/ruby/gems/3.5.0+0/gems/rspec-core-3.13.3/lib:/ydah/.rbenv/versions/3.5-dev/lib/ruby/gems/3.5.0+0/gems/rspec-support-3.13.2/lib /ydah/.rbenv/versions/3.5-dev/lib/ruby/gems/3.5.0+0/gems/rspec-core-3.13.3/exe/rspec spec/lrama/bitmap_spec.rb spec/lrama/command_spec.rb spec/lrama/context_spec.rb spec/lrama/counterexamples_spec.rb spec/lrama/diagram_spec.rb spec/lrama/grammar/code_spec.rb spec/lrama/grammar/rule_builder_spec.rb spec/lrama/grammar/symbol_spec.rb spec/lrama/grammar/symbols/resolver_spec.rb spec/lrama/integration_spec.rb spec/lrama/lexer/location_spec.rb …
```
=> Fix some warnings: assigned but unused variable

lib/lrama/states.rb
`error_symbol` is a terminal symbol then no need to check gotos.
=> Use `term_transitions` instead of `transitions`

lib/lrama/tracer.rb, lib/lrama/tracer/actions.rb, lib/lrama/tracer/closure.rb, lib/lrama/tracer/only_explicit_rules.rb, lib/lrama/tracer/rules.rb, lib/lrama/tracer/state.rb, sig/generated/lrama/tracer.rbs, sig/generated/lrama/tracer/actions.rbs, sig/generated/lrama/tracer/closure.rbs, sig/generated/lrama/tracer/only_explicit_rules.rbs, sig/generated/lrama/tracer/rules.rbs, sig/generated/lrama/tracer/state.rbs
This PR include two kind of fixes.
1. Fix type of rest keyword parameter `**Type` means type of keyword parameter value. Then `**Hash[Symbol, bool]` means `Symbol: Hash[Symbol, bool]`. What these methods expect is `Symbol: bool` so `**bool` is correct.
2. Declare optional keyword with `?key: bool` This correct way to declare optional keyword parameter.
=> Fix tracer class type declarations

lib/lrama/reporter/states.rb
* Removing local variable type annotations by removing intermediate tuple local variables
* Remove needless `#uniq` method call
* Move early return to the first
=> Refactor "lib/lrama/reporter/states.rb"

lib/lrama/state.rb, lib/lrama/state/inadequacy_annotation.rb, lib/lrama/states.rb, sig/generated/lrama/state.rbs, sig/generated/lrama/state/inadequacy_annotation.rbs, sig/generated/lrama/states.rbs
Optimizing compute_ielr.
When I ran it in my local environment as a test, the execution time was reduced to about 6-7 minutes.
```
$ time bundle exec lrama -D lr.type=ielr parse.y
bundle exec lrama -D lr.type=ielr parse.y  377.91s user 0.67s system 99% cpu 6:18.84 total
```
=> Optimize `compute_ielr`

lib/lrama/counterexamples.rb
Type declarations are written as rbs so these comments are useless anymore.
=> Remove needless comments

lib/lrama/state.rb, lib/lrama/state/inadequacy_annotation.rb, lib/lrama/states.rb, sig/generated/lrama/state.rbs, sig/generated/lrama/state/inadequacy_annotation.rbs
- Remove unnecessary re-computation
- `compute_follow_kernel_items`
- `compute_always_follows`
- `compute_goto_follows`
- Check if the contribution matrix is potential before propagation
```sh
$ time bundle exec lrama --trace=time -D lr.type=ielr parse.y
parse    0.43902 s
parse    0.00316 s
compute_lr0_states    0.40920 s
compute_direct_read_sets    0.07128 s
compute_reads_relation    0.01224 s
compute_read_sets    0.02581 s
compute_includes_relation    0.11171 s
compute_lookback_relation    0.23253 s
compute_follow_sets    0.08286 s
compute_look_ahead_sets    0.86599 s
compute_conflicts    0.00491 s
compute_default_reduction    0.00237 s
compute_predecessors    0.11527 s
compute_follow_kernel_items    0.47898 s
compute_always_follows    0.41872 s
compute_goto_follows    1.12686 s …
```
=> Optimize `split_states`

lib/lrama/counterexamples.rb, lib/lrama/counterexamples/triple.rb, lib/lrama/grammar/symbol.rb, lib/lrama/states/item.rb, sig/generated/lrama/counterexamples.rbs, sig/generated/lrama/counterexamples/triple.rbs, sig/generated/lrama/grammar/symbol.rbs
`Lrama::Counterexamples#follow_l` is one of bottlenecks of `Lrama::Counterexamples#shortest_path`. This commit includes these optimizations.
* Use Bitmap to manage `precise_lookahead_set` of counterexamples
* Precompute `number_bitmap` of `Lrama::Grammar::Symbol`
* Memoized some methods of `Lrama::States::Item`
In both profiles, calculation of counterexamples are interrupted because whole calculation takes too long time, so total number of samples are different.
Before:
```
$ stackprof tmp/stackprof-cpu-myapp_before.dump --method "Lrama::Counterexamples#shortest_path"
Lrama::Counterexamples#shortest_path (yui-knk/lrama/lib/lrama/counterexamples.rb:273)
samples:  6157 self (15.2%)  /   15260 total (37.7%)
callers:
15260  (  100.0%)  Lrama::Counterexamples#reduce_reduce_examples
9170  ( …
```
=> Optimize `Lrama::Counterexamples#follow_l`

lib/lrama/counterexamples.rb, lib/lrama/counterexamples/triple.rb, sig/generated/lrama/counterexamples/triple.rbs
Pass `StateItem` to `Triple.new` so that the number of `StateItem` instance creation decreases.
Before:
```
$ stackprof tmp/stackprof-cpu-myapp.dump --method "Lrama::Counterexamples#shortest_path"
Lrama::Counterexamples#shortest_path (yui-knk/lrama/lib/lrama/counterexamples.rb:273)
samples:  2752 self (21.5%)  /   4854 total (37.9%)
callers:
4854  (  100.0%)  Lrama::Counterexamples#reduce_reduce_examples
3345  (   68.9%)  Hash#each_key
callees (2102 total):
3362  (  159.9%)  Set#each
518  (   24.6%)  Lrama::Counterexamples::Triple#state_item
256  (   12.2%)  Class#new
251  (   11.9%)  Set#include?
241  (   11.5%)  #<Class:0x0000000104f1b698>.new
219  (   10.4%)  #<Class:0x0000000104f1c598>.new
196  (    9.3%)  Lrama::Counterexamples#reachable_state_items
128  (    6.1%)  Struct#hash
107 …
```
=> Suppress `StateItem` instance creation

lib/lrama/counterexamples.rb, lib/lrama/counterexamples/path.rb, lib/lrama/counterexamples/start_path.rb, sig/generated/lrama/counterexamples/path.rbs
Lookahead-sensitive path candidate was managed by array of `Path`. It needed to create array every time when new candidate was found. This was one of bottlenecks of `Lrama::Counterexamples#shortest_path`. This commit adds `parent` field to `Path` so that list of paths can be iterated by `parent`.
=> Don't create array for each lookahead-sensitive path candidate

lib/lrama/counterexamples.rb
Check a triple is already visited before enqueue it so that the number of while loop is reduced.
=> Optimize counter examples iteration of candidates

lib/lrama/counterexamples.rb, lib/lrama/counterexamples/path.rb, lib/lrama/counterexamples/start_path.rb, sig/generated/lrama/counterexamples/path.rbs
Previous state is accessible via `parent`.
=> Remove unused `from_state_item` from `Path`

lib/lrama/counterexamples.rb
Using `StateItem#type` makes intention clear when searching shortest path from other path.
=> Use `StateItem#type` for shortest path search method

lib/lrama/counterexamples.rb, lib/lrama/counterexamples/example.rb, sig/generated/lrama/counterexamples.rbs
This change increases 3% - 25% iteration count of reduce conflict path search for ruby parse.y size grammar on my machine.
Before:
```
Counterexamples calculation for state 97 #shortest_path: timeout of 10 sec exceeded with 477252 iteration
Counterexamples calculation for state 238 #shortest_path: timeout of 10 sec exceeded with 473998 iteration
Counterexamples calculation for state 247 #shortest_path: timeout of 10 sec exceeded with 420291 iteration
Counterexamples calculation for state 248 #shortest_path: timeout of 10 sec exceeded with 439425 iteration
Counterexamples calculation for state 250 #shortest_path: timeout of 10 sec exceeded with 509429 iteration
```
After:
```
Counterexamples calculation for state 97 #shortest_path: timeout of 10 sec exceeded with 546866 iteration …
```
=> Create StateItem in advance for optimization

lib/lrama/state.rb, lib/lrama/state/action/reduce.rb, lib/lrama/state/action/shift.rb, lib/lrama/states.rb, sig/generated/lrama/state.rbs, sig/generated/lrama/state/action/reduce.rbs, sig/generated/lrama/state/action/shift.rbs, sig/generated/lrama/states.rbs, spec/lrama/states_spec.rb
IELR computation re-calculates conflicts and default reduction of states after LALR computation.
Clear these information before IELR computation to avoid duplicated conflicts information is stored into states.
=> Clear conflicts information of states before IELR computation

lib/lrama/state.rb, sig/generated/lrama/state.rbs
Clearing the entire cache will adversely affect subsequent fetches of follow_kernel_items, etc.
=> Update transition caches instead of clearing

lib/lrama/counterexamples.rb, lib/lrama/counterexamples/state_item.rb, lib/lrama/counterexamples/triple.rb, sig/generated/lrama/counterexamples.rbs, sig/generated/lrama/counterexamples/state_item.rbs, sig/generated/lrama/counterexamples/triple.rbs
Before:
```
Counterexamples calculation for state 97 #shortest_path: timeout of 10 sec exceeded with 517532 iteration
Counterexamples calculation for state 239 #shortest_path: timeout of 10 sec exceeded with 538239 iteration
Counterexamples calculation for state 248 #shortest_path: timeout of 10 sec exceeded with 554314 iteration
Counterexamples calculation for state 249 #shortest_path: timeout of 10 sec exceeded with 517987 iteration
Counterexamples calculation for state 251 #shortest_path: timeout of 10 sec exceeded with 546731 iteration
```
After:
4 of 5 are not timeout anymore.
```
Counterexamples calculation for state 97 #shortest_path: timeout of 10 sec exceeded with 907481 iteration
```
=> Optimize Counterexamples

lib/lrama/reporter/terms.rb, spec/lrama/states_spec.rb
It would be great if you could add it as it would be useful to get current statistics.
```diff
0 unused
+19 Terms
+
+13 Non-Terminals
+
11 Unused Terms
0 YYerror
```
=> Add output for terms and non-terminals count in report

lib/lrama/parser.rb, parser.y, spec/fixtures/common/basic.y, spec/lrama/lexer_spec.rb, spec/lrama/parser_spec.rb
Fixes: https://github.com/ruby/lrama/issues/671
Add following style %define
```yacc
%define variable {value}
```
=> Add support for `%define variable {value}`

lib/lrama/grammar/symbol.rb, lib/lrama/reporter/rules.rb, sig/generated/lrama/grammar/symbol.rbs, spec/lrama/states_spec.rb
This PR adds support for reporting Rule Usage Frequency.
I find this useful when taking a Report as a statistic.
I hope that knowing what terminators and non-terminators are used in the generation rules will give you some insight into the nature of the language.
```
Rule Usage Frequency
0 tSTRING (4 times)
1 keyword_class (3 times)
2 keyword_end (3 times)
3 '+' (2 times)
4 string (2 times)
5 string_1 (2 times)
6 '!' (1 times)
7 '-' (1 times)
8 '?' (1 times)
9 EOI (1 times)
10 class (1 times)
11 program (1 times)
12 string_2 (1 times)
13 strings_1 (1 times)
14 strings_2 (1 times)
15 tNUMBER (1 times)
```
=> Add support for reporting Rule Usage Frequency

lib/lrama/grammar/stdlib.y, spec/fixtures/parameterized/stdlib/ioption.y, spec/lrama/parser_spec.rb
This is a Rule also provided by Menhir, and is an Inline rule that is deployed inline as follows
```
program: ioption(X)
=>
program: %empty
program: X
```
refs: https://github.com/let-def/menhir/blob/e8ba7bef219acd355798072c42abbd11335ecf09/src/standard.mly#L33-L41
=> Add ioption support to the Standard library

.github/workflows/test.yaml
Refs: https://github.com/ruby/ruby/pull/13321
=> Update minimum BASERUBY version to 3.1 in workflow configuration

lib/lrama/parser.rb, parser.y, spec/fixtures/common/precedence.y, spec/lrama/lexer_spec.rb, spec/lrama/parser_spec.rb
Fixes: https://github.com/ruby/lrama/issues/674
=> Add support for allowing multiple tags to be mixed on one line in precedence declarations

lib/lrama/parser.rb, parser.y
Before:
```
$ bundle exec exe/lrama --trace=time sample/calc.y
parse    0.00224 s
parse    0.00414 s
...
```
After:
```
$ bundle exec exe/lrama --trace=time sample/calc.y
parse 'calc.y'    0.00234 s
parse 'stdlib.y'    0.00439 s
...
```
=> Include grammar file name into the duration report labels

lib/lrama/state/reduce_reduce_conflict.rb, sig/generated/lrama/state/reduce_reduce_conflict.rbs
So that we can change `symbols`, `reduce1` and `reduce2` to be a mandatory argument.
=> Make `ReduceReduceConflict` to be plain object

lib/lrama/grammar.rb
I don't think this raise can happen. Maybe you still have a debug raise?
For example, I tried the following test case, but this if statement never turned out to be true:
case1:
```
%precedence object
%%
json: object
;
object: '{' members? '}'
;
```
case2:
```
%type <str> object
%precedence object
%%
json: object
;
object: '{' members? '}'
;
```
=> Remove unnecessary raise statement in set_precedence method

lib/lrama/grammar.rb, spec/lrama/grammar_spec.rb
Before:
```
[BUG] Precedence of expression (line: 10) is not term. It should be term.
```
After:
```
[BUG] Precedence expression (line: 10) is defined for nonterminal (line: 1). Precedence can be defined for only terminal symbol.
```
=> Make error messages more understandable

lib/lrama/counterexamples/example.rb, lib/lrama/digraph.rb, lib/lrama/grammar.rb, lib/lrama/grammar/code/destructor_code.rb, lib/lrama/grammar/code/printer_code.rb, lib/lrama/grammar/code/rule_action.rb, lib/lrama/grammar/counter.rb, lib/lrama/grammar/percent_code.rb, lib/lrama/grammar/rule.rb, lib/lrama/grammar/rule_builder.rb, lib/lrama/grammar/type.rb, lib/lrama/state.rb, lib/lrama/state/action/goto.rb, lib/lrama/state/action/reduce.rb, lib/lrama/state/action/shift.rb, lib/lrama/states.rb, lib/lrama/tracer/duration.rb, sig/generated/lrama/grammar/rule.rbs, sig/generated/lrama/grammar/rule_builder.rbs, spec/fixtures/inlining/parameterized_args_include_inline.y, spec/lrama/parser_spec.rb
Support following:
```
%rule %inline op : '+'
| '-'
;
%%
operation : op?
;
```
=> Support parameterized rule's arguments include inline

lib/lrama/grammar.rb, spec/lrama/grammar_spec.rb
Fixes: https://github.com/ruby/lrama/pull/704#discussion_r2249042683
=> Change the method `validate_no_precedence_for_nterm! `to search `nterms` instead of the Rule's LHS

lib/lrama/grammar.rb, lib/lrama/grammar/precedence.rb, lib/lrama/parser.rb, parser.y, sig/generated/lrama/grammar.rbs, sig/generated/lrama/grammar/precedence.rbs, spec/lrama/grammar_spec.rb
Example:
```
%{
// Prologue
%}
%union {
int i;
}
%left tSTRING tNUMBER
%precedence tSTRING
%right tIDENTIFIER
%nonassoc tSTRING tNUMBER
%%
program: tNUMBER
;
```
Before:
```
$ exe/lrama example.y
```
After:
```
❯ exe/lrama tmp/a.y
[BUG] %precedence redeclaration for tSTRING (line: 8) previous declaration was %left (line: 7)
[BUG] %nonassoc redeclaration for tSTRING (line: 10) previous declaration was %left (line: 7)
[BUG] %nonassoc redeclaration for tNUMBER (line: 10) previous declaration was %left (line: 7)
```
=> Change to raise an error if `%precedence` is set more than once for the same terminal symbol

lib/lrama/grammar.rb, lib/lrama/lexer.rb, lib/lrama/parser.rb, parser.y, sig/generated/lrama/grammar.rbs, spec/fixtures/common/start.y, spec/lrama/grammar_spec.rb, spec/lrama/parser_spec.rb
Fixes: https://github.com/ruby/lrama/issues/568
=> Add support Start-Symbol: `%start`

lib/lrama/states.rb, sig/generated/lrama/states.rbs
Extract these method calls to `#compute_look_ahead_sets` and rename `#compute_look_ahead_sets` to `#compute_la`.
=> Extract method calls for look ahead sets computation

lib/lrama/counterexamples.rb, lib/lrama/counterexamples/derivation.rb, lib/lrama/counterexamples/example.rb, lib/lrama/counterexamples/state_item.rb, lib/lrama/counterexamples/triple.rb, lib/lrama/state.rb, lib/lrama/state/action/goto.rb, lib/lrama/state/action/reduce.rb, lib/lrama/state/action/shift.rb, lib/lrama/state/inadequacy_annotation.rb, lib/lrama/state/item.rb, lib/lrama/states.rb, sig/generated/lrama/counterexamples.rbs, sig/generated/lrama/counterexamples/derivation.rbs, sig/generated/lrama/counterexamples/example.rbs, sig/generated/lrama/counterexamples/state_item.rbs, sig/generated/lrama/counterexamples/triple.rbs, sig/generated/lrama/state.rbs, sig/generated/lrama/state/action/goto.rbs, sig/generated/lrama/state/action/reduce.rbs, sig/generated/lrama/state/action/shift.rbs, sig/generated/lrama/state/inadequacy_annotation.rbs, sig/generated/lrama/state/item.rbs, sig/generated/lrama/states.rbs
`Item` is held by `State` thne it's better to place `Item` under `State` rather than `States`.
=> Move `Item` from `States` to `State`

lib/lrama/warnings.rb, lib/lrama/warnings/useless_precedence.rb, sig/generated/lrama/warnings/useless_precedence.rbs, spec/fixtures/states/precedence_unused.y, spec/fixtures/states/precedence_used.y, spec/fixtures/states/precedence_without_prec.y, spec/lrama/warnings/useless_precedence_spec.rb
Example1:
```
%{
#include <stdio.h>
#include <stdlib.h>
int yylex(void);
void yyerror(const char *s);
%}
%union {
int i;
}
%token NUMBER
%precedence PRECEDENCE
%%
program:
NUMBER %prec PRECEDENCE
;
%%
int main(void) {
printf("Parser ready. Enter expressions:\n");
return yyparse();
}
void yyerror(const char *s) {
fprintf(stderr, "Error: %s\n", s);
}
```
Before:
```
❯ exe/lrama -W tmp/example.y
```
After:
```
❯ exe/lrama -W tmp/example.y
Precedence PRECEDENCE (line: 14) is defined but not used in any rule.
```
Example2:
```
%{
#include <stdio.h>
#include <stdlib.h>
int yylex(void);
void yyerror(const char *s);
%}
%union {
int i;
}
%token NUMBER
%precedence PRECEDENCE
%%
program:
NUMBER
;
%%
int main(void) {
printf("Parser ready. Enter expressions:\n");
return yyparse();
}
void yyerror(const …
```
=> Add support for precedence handling and warnings for unused precedences

lib/lrama/lexer/location.rb, sig/generated/lrama/lexer/location.rbs, spec/lrama/grammar/rule_builder_spec.rb, spec/lrama/lexer/location_spec.rb, spec/lrama/parser_spec.rb
Before:
```
parse.y:31:78: multiple User_code after %prec
class : keyword_class { code 4 } tSTRING '?' keyword_end %prec tEQ { code 5 } { code 6 }
^
error_messages/parse.y:7:9: %empty on non-empty rule
program: %empty %empty
^^^^^^
```
After:
```
parse.y:31:78: multiple User_code after %prec
31 | class : keyword_class { code 4 } tSTRING '?' keyword_end %prec tEQ { code 5 } { code 6 }
|                                                                               ^
error_messages/parse.y:7:9: %empty on non-empty rule
7 | program: %empty %empty
|          ^~~~~~
```
=> Improve format for generate_error_message

lib/lrama/lexer.rb, spec/lrama/lexer_spec.rb
Previously, when there are trailing whitespace characters at the end of line, lrama miscounted the line number.
```
// <=== Place whitespace here (and do not place this comment)
%{puts("Hello");
%}
%%
a: ‘-’;
```
```
$ ./exe/lrama t.y && less y.tab.c
*snip*
/* First part of user prologue.  */
#line 1 "t.y"  // <=== This should be #line 2
puts("Hello");
*snip*
```
=> Fix line number counting when there are trailing spaces

lib/lrama/bitmap.rb
This PR is just a change for simplicity. Use `Array.new(n) {|i| int[i] ==i}`.
=> Refactor Bitmap#to_bool_array for conciseness
