ruby/lrama

lrama.gemspec
Follow up of https://github.com/yui-knk/lrama/pull/4
=> Update required_ruby_version to 2.5 or later

.github/workflows/test.yaml, Gemfile, Steepfile, sig/lrama/bitmap.rbs
I introduced RBS (`bitmap.rb` only)
- Add RBS and Steep
- Run `steep check` with ruby HEAD on CI
I plan to eventually change `check "lib/lrama/bitmap.rb"` in steepfile to `lib`.
=> Add RBS and Steep check on CI

sample/calc.output
This file is generated by `lrama --report=all sample/calc.y`. I hope someone has an interest in LR parser internal structure.
=> Add "sample/calc.output"

lib/lrama/states.rb
Found by trial application of Steep
=> Remove unused method

lib/lrama/grammar.rb, lib/lrama/states.rb, lib/lrama/states_reporter.rb, spec/lrama/states_spec.rb
This PR is fix some typos.
- s/Igonre/Ignore/
- s/dupulicated/duplicated/
- s/creted/created/
- s/Reprot/Report/
- s/nubmer/number/
=> Fix some typos

lib/lrama/parser.rb, lib/lrama/parser/token_scanner.rb
* Separated TokenScanner class from lrama/parser.rb file
=> Refactor lrama/parser.rb

Steepfile, sig/lrama/report.rbs
=> Add report.rbs

lib/lrama/parser.rb
=> remove typo

spec/integration/ruby_spec.rb, template/bison/yacc.c, template/bison/yacc.h
Backport of 60fcdda17ffa9e764b2ba396271697dcce5b725c.
=> Embed the version of Lrama

lib/lrama/lexer.rb, lib/lrama/lexer/token.rb
- Separate Token class from lrama/lexer.rb(ref: [ruby-jp comment](https://ruby-jp.slack.com/archives/C057TBFEMMX/p1687573185462809?thread_ts=1687499845.609649&cid=C057TBFEMMX))
- Add lrama/lexer/token.rb
=> Refactor lrama/lexer.rb

spec/lrama/integration_spec.rb
Add integration test which actually generates executable file then checks its stdout.
=> Add integration test

exe/lrama, lib/lrama/command.rb, spec/lrama/command_spec.rb, spec/lrama/integration_spec.rb
* Fix report_file name when file name is specified after '-'
=> Refactor Command class

lib/lrama/grammar/rule.rb
Prefer safe navigation in precedence and translated_code, and symbol to proc in as_comment.
=> Refactor Lrama::Grammar::Rule

lib/lrama/command.rb, spec/lrama/command_spec.rb, spec/spec_helper.rb
Before this commit
```
$ lrama --version
File should be specified
```
After
```
$ lrama --version
lrama 0.5.4
```
=> Fix to print version when version option is passed

Steepfile, rbs_collection.lock.yaml, sig/lrama/digraph.rbs
Added type information to digraph.rb.
You may need to modify the actual code in some cases, since nil is entered in some places.
Currently nil is allowed for type checking.
=> Add digraph.rbs

spec/lrama/command_spec.rb
=> Stop creating parser file on top directory

lib/lrama/new_lexer.rb, lib/lrama/new_parser.rb, parser.y
Token generation was moved from Parser to Lexer in order to simplify the description of Parser.
=> Build Lrama::Lexer::Token in Lrama::NewLexer#next_token

lib/lrama/new_parser.rb, parser.y
Format racc grammar file of parser.
Only the appearance is changed, not the behavior.
=> Format parser.y

lib/lrama/new_lexer.rb, lib/lrama/new_parser.rb, parser.y, spec/lrama/new_parser_spec.rb
- Parse single-line comments
- Set %expect
=> Replace NewPerser with Parser #1

lib/lrama/new_lexer.rb, lib/lrama/new_parser.rb, parser.y, spec/lrama/new_parser_spec.rb
- Skip %empty token as a comment
- Set collect line when parsing empty rhs line
=> Replace NewParser With Parser #2

lib/lrama/new_lexer.rb, spec/lrama/new_parser_spec.rb
- Parse character in user code
=> Replace NewParser with Parser #5

lib/lrama/new_lexer.rb, lib/lrama/new_parser.rb, parser.y, spec/lrama/states_spec.rb
=> Replace NewParser with Parser (`%precedence`)

.github/workflows/test.yaml, Rakefile, lib/lrama/command.rb, lib/lrama/option_parser.rb, lib/lrama/options.rb, lib/lrama/parser.rb, parser.y, spec/lrama/option_parser_spec.rb
- Display Racc's debug output
- Set --debug flag to enable it
=> Add debug mode to command

lib/lrama/parser.rb, parser.y
Follow up: https://github.com/ruby/lrama/pull/168/commits/9eff5048c160dc5b339bdfbdbf6e98fe0aff421f
=> Extract curly brace begin process to a private method

lib/lrama/parser.rb, parser.y
Rule for "%require" is duplicated.
=> Resolve S/R conflicts

spec/lrama/grammar/code_spec.rb
Test for RuleAction is implemented.
=> Remove TODO

lib/lrama/grammar/parameterizing_rule_builder.rb, lib/lrama/grammar/parameterizing_rule_rhs_builder.rb, lib/lrama/parser.rb, parser.y, sig/lrama/grammar/parameterizing_rule_builder.rbs, sig/lrama/grammar/parameterizing_rule_rhs_builder.rbs, spec/fixtures/integration/user_defined_parameterizing_rules.l, spec/fixtures/integration/user_defined_parameterizing_rules.y, spec/fixtures/parameterizing_rules/user_defined.y, spec/lrama/integration_spec.rb, spec/lrama/parser_spec.rb
Follow up: https://github.com/ruby/lrama/pull/289
=> Fix failed integration test for user defined parameterizing rules

lib/lrama/grammar/rule_builder.rb, lib/lrama/lexer/token.rb, lib/lrama/lexer/token/instantiate_rule.rb, lib/lrama/parser.rb, parser.y, sig/lrama/grammar/parameterizing_rule_builder.rbs, sig/lrama/grammar/parameterizing_rule_resolver.rbs, sig/lrama/grammar/parameterizing_rules/builder.rbs, sig/lrama/grammar/parameterizing_rules/builder/base.rbs, sig/lrama/lexer/token/instantiate_rule.rbs
This is not parameterizing but generating rules from parameterizing rule and arguments.
=> Rename Parameterizing to InstantiateRule

lib/lrama/lexer/location.rb, sig/lrama/lexer/location.rbs, spec/lrama/lexer/location_spec.rb
Follow: https://github.com/codespell-project/codespell/pull/3263
=> carrets->carets

lib/lrama/command.rb
Full backtrace is too verbose when invoking as a command.
Just show the message unless `--debug` option is given.
=> Do not show backtrace in the command

lib/lrama/grammar.rb
Follow up: https://github.com/codespell-project/codespell/pull/3281
=> Fix a typo

.github/workflows/test.yaml
Follow up: https://github.com/ruby/ruby/commit/b4ed5b7dfe9ca01ef48922d1b2c154767b7e4e86
=> Bump the required BASERUBY version to 2.7

.github/workflows/test.yaml
Ref: https://github.com/ruby/ruby/pull/9976
=> Minimal BASERUBY version was updated to 3.0

spec/lrama/context_spec.rb, spec/lrama/counterexamples_spec.rb, spec/lrama/states_spec.rb
Follow up: https://github.com/ruby/lrama/pull/424
=> Use `StringIO.new` instead of `""`

Gemfile
https://github.com/ruby/rbs/releases/tag/v3.5.1
https://github.com/ruby/rbs/releases/tag/v3.5.0
=> Bump rbs from v3.4.4 to v3.5.1

lib/lrama/parser.rb, parser.y
This pull request uses `Option:? `
=> Use ";"? instead of rhs

Gemfile
https://github.com/soutaro/steep/releases/tag/v1.7.0
https://github.com/soutaro/steep/releases/tag/v1.7.1
=> Bump steep from v1.6.0 to v1.7.1

lib/lrama/grammar.rb, lib/lrama/grammar/rule.rb, lib/lrama/lexer.rb, lib/lrama/output.rb, lib/lrama/parser.rb, parser.y, sample/calc.y, sample/parse.y, sig/lrama/grammar.rbs, sig/lrama/grammar/rule.rbs, spec/fixtures/integration/after_shift.y, spec/fixtures/integration/contains_at_reference.l, spec/fixtures/integration/contains_at_reference.y, spec/fixtures/integration/destructors.y, spec/fixtures/integration/error_recovery.y, spec/fixtures/integration/line_number.y, spec/fixtures/integration/named_references.y, spec/fixtures/integration/parameterizing_rules.y, spec/fixtures/integration/params.y, spec/fixtures/integration/printers.y, spec/fixtures/integration/prologue_epilogue_optional.y, spec/fixtures/integration/typed_midrule_actions.y, spec/fixtures/integration/user_defined_parameterizing_rules.y, spec/lrama/integration_spec.rb
fix: https://github.com/ruby/lrama/issues/429
=> Ensure compatibility with Bison for `%locations`

NEWS.md
This PR add NEWS v0.6.6~v0.6.9
=> Add NEWS v0.6.6~v0.6.9

lib/lrama/parser.rb, parser.y
Use racc's new grammar: `?`
- https://github.com/ruby/racc/pull/222
=> Use `"%empty"?` instead of `empty`

lib/lrama/parser.rb, parser.y
=> Use `TAG? token_declaration+` instead of `token_declaration+` and `TAG token_declaration+`

lib/lrama/parser.rb, parser.y, spec/lrama/diagnostics_spec.rb
=> Refactoring with option in parser.y

Gemfile
=> Bump steep gem version to 1.9.2

lib/lrama/states_reporter.rb, sig/generated/lrama/states_reporter.rbs
Just add RBS type annotations.
=> Add RBS type annotations to StatesReporter methods and generate RBS signature

lib/lrama/grammar/code/no_reference_code.rb, lib/lrama/grammar/code/printer_code.rb, sig/generated/lrama/grammar/code/no_reference_code.rbs, sig/generated/lrama/grammar/code/printer_code.rbs
Follow up of https://github.com/ruby/lrama/pull/577
=> Fix type annotations

lib/lrama/parser.rb, parser.y, spec/fixtures/common/basic.y, spec/lrama/lexer_spec.rb
Fix: https://github.com/ruby/lrama/issues/673
=> Allow multiple `;` for Bison compatibility

.github/workflows/test.yaml
Fixes: https://github.com/ruby/lrama/actions/runs/15225718911/job/42827501889?pr=683
=> Fix MSYS2 setup by disabling auto-update and adding manual recovery steps

doc/Index.md
Refs:
* https://github.com/ruby/ruby/pull/13321
* https://github.com/ruby/lrama/pull/683
=> Update minimum BASERUBY version referred in "doc/Index.md"

.github/workflows/test.yaml
Fixes: https://github.com/ruby/lrama/actions/runs/17357822596/job/49273393000
Fixes: https://github.com/ruby/lrama/actions/runs/17358238516/job/49274450221
=> Fix CI error for windows
